version: "3"

services:
  shop:
    image: dockware/flex:latest
    container_name: ${SHOP_NAME}_shop
    volumes:
      - ".:/var/www/html/"
    ports:
      - "80:80"
      - "23:22"
      - "8888:8888"
      - "9998:9998"
      - "8080:8080"
  shop_db:
    image: mysql:5.7
    container_name: ${MYSQL_DATABASE}_db
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3307:3306'

